# Generated by Django 4.2.6 on 2023-10-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaAPP', '0005_book_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
